# Generated by Django 3.0.5 on 2020-04-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20200423_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='name',
            field=models.SlugField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
