# Generated by Django 3.0.5 on 2020-04-27 01:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20200425_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None),
        ),
    ]
