# Generated by Django 3.0.5 on 2020-04-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_remove_pin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='tags',
            field=models.ManyToManyField(related_name='libraries', to='pins.Tag'),
        ),
    ]
